### ISSUE TITLE
Woocommerce search not working.

### ISSUE THREAD

**Issue by Hammer1980** [Rundiz-WP/bootstrap-basic#32] opened 2024-04-23 23:40 UTC
If I search 'Mix', even with a woocommerce search plug in the out put is below.

"Create your own bundle with Mix and Match.

Create your own bundle with Mix and Match.

MIX & MATCH

MIX & MATCH"

There are two products with the term in with one of each of the above in title and description.

This is all it shows. Just plain text. It works in other themes, just not this one. It does not show the woocommerce products.
Any idea to make this work ?  Works fine in Storefront so am sure its a theme issue.

**Comment by ve3** [comment] 2024-04-24 01:48
It is not possible that all themes will be supported WooCommerce. 
For example, one of popular Bootstrap ( Flat Bootstrap by XtremelySocial ) still not fully supported. The search result is just product title, description same as this theme.

You have to search for theme that has marked as WooCommerce supported. Example ( https://wordpress.org/themes/search/woocommerce/? ).

**Closed by ve3** 2024-04-24 01:48 UTC

**Comment by ve3** [comment] 2024-04-24 01:53
This theme has nothing about search result modification. If you disable all other plugins except Woo then it will be able to search the product but search result did not display product's thumbnail. It still be able to click on the link to see product description page.

So, what you said _It does not show the woocommerce products_ isn't true. WordPress can search across any different post types. Try to disable other plugins that may interfere the search result.

**Comment by Hammer1980** [comment] 2024-04-24 02:09
Hello. Thanks for the reply and the great theme. It is ideal for what I need but I really need to show the products on the search page. Even with plugins off it doesn't work. I have been 3 days trying to figure it out but don't have the skills.  There are no links from the page it just literally the words involving 'mix' for each of the products.  I was really hoping there was something simple I could do to fix this issue but if the developer isn't able to do ti then I have no chance !!  Thanks again.  I just wanted to display the products like on a category page.

**Comment by Hammer1980** [comment] 2024-04-24 02:11
> It is not possible that all themes will be supported WooCommerce. For example, one of popular Bootstrap ( Flat Bootstrap by XtremelySocial ) still not fully supported. The search result is just product title, description same as this theme.
> 
> You have to search for theme that has marked as WooCommerce supported. Example ( https://wordpress.org/themes/search/woocommerce/? ).

Yes I looked at that theme after I had issues with yours.  I really love it, everything else is perfect for what I need but I can't use it without the products appearing like the rest of the shop in the search.  Is it a really complex thing to do ?

**Comment by ve3** [comment] 2024-04-24 02:24
### These are screenshots for this theme.
https://postimg.cc/wyw2rFcs
Category page.

https://postimg.cc/vxDhw932
Search result page.

### These are screenshots for Flat Bootstrap theme.
https://postimg.cc/SjtV7TxB
Category page.

https://postimg.cc/yWNvR4sh
Search result page.

---

From screenshots our theme (this including Bootstrap Basic4 but I did not capture it) have same result, 
they can display product link from category, 
they can display search result that contain product with title, description, and link.

So, it is not the problem from theme. You have to disable **ALL** the plugins exclude WooCommerce itself and see that what plugin cause your problem.
If you had issue with this theme you had issue with Flat Bootstrap too because they have same result just different design. See from screenshot.

**Comment by Hammer1980** [comment] 2024-04-24 02:41
All the plugins were off apart from woocommerce.  Bootstrap 4 I got a link even with plug ins, bootstrap just the lines with no links.  

Is it impossible to display the product itself like in the categories ?  Where would I look to try and make it work. I really would like to use this theme as a base but I can't without the product displaying as it does elsewhere in the search.

Thanks for the replies. I must go te bed 3.41 am !!  Got to be up at 8 :)

**Comment by ve3** [comment] 2024-04-24 02:53
If you want search product in categories (I don't know how or what it is) and it seems to be more specific than normal search by WordPress then you need plugin or create plugin yourself. It is not the task from any theme.

The problem that display the lines (what lines?) with no links seems to be from other plugins because I installed WordPress with WooCommerce and this Bootstrap Basic theme and found no problem as seen in screenshot.

I can't help anything if **I can't re-produce the problem**. And your problem seems to come from something else than this theme.

I don't see screenshot of your problem. 
**I can't reproduce your problem.** 
I don't even know what exactly is your problem? Because from what you describe it is just that this and other Bootstrap theme did not fully supported WooCommerce. (Not all theme fully supported - it's normal.)
So, sorry but I couldn't help you more because of these reason.

**Comment by Hammer1980** [comment] 2024-04-24 08:52
Hello, the issue with the missing 'link' on Bootstrap is css. I don't need search to be for categories, I was trying to explain of what I need search too look like.... and look like you showed me in your screenshots in categories.  I am not asking for you to alter your theme, I am asking where I would need to edit and try to change it myself.   Is it very complicated ?  

Thanks again for your replies.

**Comment by ve3** [comment] 2024-04-24 13:48
From the original post you have the details about _It does not show the woocommerce products_ and I was answered that it is not true.   
I show you both category and search result screenshots (2 ss) NOT just categories. I'm already show you that it work and it is not a problem for just this theme as you said. This also happens with other themes.

Now CSS??

Can you show me or provide a lot more information about  
What page you have this problem?  
How is your screen currently? Highlight on the problem.  
And How you want it to be? (What you expected to be?)   

I cannot know because I don't see your screen and you keep telling about search result page which work as expected.  
I cannot help anything until you provide more info.

**Comment by Hammer1980** [comment] 2024-04-24 21:52
Hello, I found the problem not showing the link, there was a problem with some css I copied and pasted that hid the link.  My error.

I get the impression you think I am finding fault with your work. I promise you I am not. You have made a great job. Thank you.

I was just asking if their is a way to make the search look the same as the category does on the page, and I understand you are not going to make it part of the the theme, maybe let me know where I should look to try and alter the files myself.

**Comment by ve3** [comment] 2024-04-25 02:54
To make search look the same as category. In this case I understand that you mean WooCommerce's category page.

I can give you limited instruction/info because this is about to [design a WooCommerce theme](https://developer.woocommerce.com/docs/classic-theme-development-handbook/) which I have no idea about them. 

First you have to look at [**Template Hierarchy**](https://developer.wordpress.org/themes/basics/template-hierarchy/) from WordPress to know that how each template file will be loaded.

The search page is currently using **search.php** file.  
The search result part that showing posts/product is the part that use this code `get_template_part('content', 'search');`. It will be try to looking for **content-search.php**, if not found then using **content.php**.  
Reference of [`get_template_part()`](https://developer.wordpress.org/reference/functions/get_template_part/).  

To design based on category page. This seems to be a problem now. WC use template file **page.php** as based template and the design on category page is using their own template which I have zero knowledge about this. You have to read in their developer document page as linked above.
